redis:
    image: redis
    ports:
        - "6379:6379"
es:
    image: elasticsearch
    ports:
        - "9200:9200"
mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=pass

